version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - sam build --template-file search-function.yaml --use-container
      - sam package --output-template-file search-function-output.yaml --s3-bucket hollers-artifacts-bucket-gl

artifacts:
  type: zip
  files:
    - upload-to-search.yaml
    - upload.yaml